In [2]:
from fastbook import *

# Tensors

In [3]:
t = tensor([[[1,2],[3,4]],[[5,6],[7,8]]]).float()

In [4]:
t

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [5]:
t.mean((0,1))

tensor([4., 5.])

In [6]:
t

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

# Matrix Multiplication

In [9]:
t*t

tensor([[[ 1.,  4.],
         [ 9., 16.]],

        [[25., 36.],
         [49., 64.]]])

In [11]:
t@t

tensor([[[  7.,  10.],
         [ 15.,  22.]],

        [[ 67.,  78.],
         [ 91., 106.]]])

In [12]:
m1 = tensor([[2, 3],[4, 5]])

In [15]:
v1 = tensor([[1], [1]])

In [16]:
m1 @ v1

tensor([[5],
        [9]])

In [18]:
help(m1.__matmul__)

Help on built-in function __matmul__:

__matmul__(...) method of torch.Tensor instance

